<?php
/**
 * @var $block \MageArab\CashDate\Block\Info\Cashondelivery
 */
?>
<dl class="payment-method cashondelivery">
    <dt class="title"><?= $block->escapeHtml($block->getMethod()->getTitle()) ?></dt>
    <?php if ($block->getCashDate()): ?>
        <dd class="content">
            <strong><?= $block->escapeHtml(__('Checkout Date')) ?></strong>
            <?= $block->escapeHtml($block->getCashDate()) ?>
        </dd>
    <?php endif; ?>
</dl>
