<?php
/**
* @var $block \MageArab\CashDate\Block\Form\Cash
*/
$instructions = $block->getInstructions();
$cashDate=$block->getCashDate();
?>
<?php if ($instructions || $cashDate): ?>
    <?php $methodCode = $block->escapeHtml($block->getMethodCode());?>
    <ul class="form-list checkout-agreements" id="payment_form_<?= /* @noEscape */ $methodCode ?>" style="display:none;">
    <?php if($instructions):?>
        <li>
            <div class="<?= /* @noEscape */ $methodCode ?>-instructions-content checkout-agreement-item-content">
                <?= /* @noEscape */ nl2br($block->escapeHtml($instructions)) ?>
            </div>
        </li>
    <?php endif;?>
    <?php if($cashDate):?>
        <li>
            <div class="<?= /* @noEscape */ $methodCode ?>-instructions-content checkout-agreement-item-content">
                <strong><?= $block->escapeHtml(__('Checkout Date')) ?></strong>
                <?= $block->escapeHtml($block->getCashDate()) ?>
            </div>
        </li>
    <?php endif;?>
    </ul>
<?php endif; ?>